"""增加签到状态字段

Revision ID: 28c43ae7c63d
Revises: 
Create Date: 2018-04-25 16:45:10.077850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28c43ae7c63d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('sign_statue', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'sign_statue')
    # ### end Alembic commands ###
